In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("../datasets/FeynmanEquations.csv")
df.head()

,Filename,Number,Output,Formula,# variables,v1_name,v1_low,v1_high,v2_name,v2_low,...,v7_high,v8_name,v8_low,v8_high,v9_name,v9_low,v9_high,v10_name,v10_low,v10_high
0,I.6.2a,1.0,f,exp(-theta**2/2)/sqrt(2*pi),1.0,theta,1.0,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I.6.2,2.0,f,exp(-(theta/sigma)**2/2)/(sqrt(2*pi)*sigma),2.0,sigma,1.0,3.0,theta,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I.6.2b,3.0,f,exp(-((theta-theta1)/sigma)**2/2)/(sqrt(2*pi)*...,3.0,sigma,1.0,3.0,theta,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I.8.14,4.0,d,sqrt((x2-x1)**2+(y2-y1)**2),4.0,x1,1.0,5.0,x2,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,I.9.18,5.0,F,G*m1*m2/((x2-x1)**2+(y2-y1)**2+(z2-z1)**2),9.0,m1,1.0,2.0,m2,1.0,...,2.0,z1,3.0,4.0,z2,1.0,2.0,NaN,NaN,NaN

In [44]:
n_vars = 5
df_tmp = df[df["# variables"] == n_vars]
variables_list = []

for i, row in df_tmp.iterrows():
    these_variables = sorted([row[f"v{i + 1}_name"] for i in range(n_vars)], key=str.lower)
    # these_variables = [row[f"v{i + 1}_name"] for i in range(n_vars)]
    variables_list.append(these_variables)

for i, var_list in enumerate(variables_list):
        print(i, var_list)

0 ['B', 'Ef', 'q', 'theta', 'v']
1 ['G', 'm1', 'm2', 'r1', 'r2']
2 ['c', 'h', 'kb', 'omega', 'T']
3 ['kb', 'n', 'T', 'V1', 'V2']
4 ['A', 'd', 'kappa', 'T1', 'T2']
5 ['Ef', 'm', 'omega', 'omega_0', 'q']
6 ['Ef', 'kb', 'n_rho', 'p_d', 'T']
7 ['c', 'epsilon', 'q', 'r', 'v']
8 ['B', 'g_', 'h', 'Jz', 'mom']
9 ['B', 'kb', 'mom', 'n_0', 'T']
10 ['B', 'kb', 'mom', 'n_rho', 'T']
11 ['I_0', 'kb', 'q', 'T', 'Volt']

In [45]:
df_tmp

,Filename,Number,Output,Formula,# variables,v1_name,v1_low,v1_high,v2_name,v2_low,...,v7_high,v8_name,v8_low,v8_high,v9_name,v9_low,v9_high,v10_name,v10_low,v10_high
11,I.12.11,13.0,F,q*(Ef+B*v*sin(theta)),5.0,q,1.0,5.0,Ef,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,I.13.12,14.0,U,G*m1*m2*(1/r2-1/r1),5.0,m1,1.0,5.0,m2,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,I.41.16,44.0,L_rad,h/(2*pi)*omega**3/(pi**2*c**2*(exp((h/(2*pi))*...,5.0,omega,1.0,5.0,T,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,I.44.4,48.0,E_n,n*kb*T*ln(V2/V1),5.0,n,1.0,5.0,kb,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,II.2.42,52.0,Pwr,kappa*(T2-T1)*A/d,5.0,kappa,1.0,5.0,T1,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,II.11.3,61.0,x,q*Ef/(m*(omega_0**2-omega**2)),5.0,q,1.0,3.0,Ef,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,II.11.20,63.0,Pol,n_rho*p_d**2*Ef/(3*kb*T),5.0,n_rho,1.0,5.0,p_d,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,II.21.32,71.0,Volt,q/(4*pi*epsilon*r*(1-v/c)),5.0,q,1.0,5.0,epsilon,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,II.34.29b,79.0,E_n,g_*mom*B*Jz/(h/(2*pi)),5.0,g_,1.0,5.0,h,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,II.35.18,80.0,n,n_0/(exp(mom*B/(kb*T))+exp(-mom*B/(kb*T))),5.0,n_0,1.0,3.0,kb,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,II.35.21,81.0,M,n_rho*mom*tanh(mom*B/(kb*T)),5.0,n_rho,1.0,5.0,mom,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,III.14.14,94.0,I,I_0*(exp(q*Volt/(kb*T))-1),5.0,I_0,1.0,5.0,q,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN